#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

cd -- "$(dirname -- "$0")/.."

echo "==> Running dotnet build"
DOTNET_ROLL_FORWARD=Major dotnet build --no-restore
