#!/usr/bin/env bash

set -euo pipefail

cd -- "$(dirname -- "$0")/.."

echo "==> Running dotnet csharpier check"
dotnet csharpier check .

echo "==> Running dotnet format"
dotnet format style --no-restore --severity info --verify-no-changes
dotnet format analyzers --no-restore --severity info --verify-no-changes
